openapi: 3.0.3
info:
  title: Api de Gerenciamento de Estoque do Senai
  version: 1.0.0
  description: "Projeto com objetivo de desenvolver um sistema web para o amorixafado
    do Senai DF. \n \n Programa feitor pela turma 3°DS - 2026"
paths:
  /api/unidade/:
    get:
      operationId: api_unidade_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Unidade'
          description: ''
    post:
      operationId: api_unidade_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Unidade'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Unidade'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Unidade'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unidade'
          description: ''
  /api/unidade/{id}/:
    get:
      operationId: api_unidade_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este unidade models.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unidade'
          description: ''
    put:
      operationId: api_unidade_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este unidade models.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Unidade'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Unidade'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Unidade'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unidade'
          description: ''
    patch:
      operationId: api_unidade_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este unidade models.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUnidade'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUnidade'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUnidade'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unidade'
          description: ''
    delete:
      operationId: api_unidade_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este unidade models.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    PatchedUnidade:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 50
    Unidade:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 50
      required:
      - id
      - nome
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
